### ISSUE TITLE
winston exceptionHandlers is not printing logs to file

### ISSUE THREAD

**Issue by likepeach789** [gremo/nest-winston#195]
## Env:
1. Node: v10.19.0
2. Nest: v7.3.2
3. Nest Winston: ^1.3.6
4. winston: ^3.3.3
5. OS: Mac

## Issue:
When i configure exceptionHandlers, the file got created but no log saving in the file.

## Configure
```javascript
import { WinstonModule } from 'nest-winston';
import * as winston from 'winston';
const path = require("path");
require('winston-daily-rotate-file');
const myFormat = winston.format.printf(info => {
  return `${info.timestamp} ${info.level} [${info.label}]: ${info.message}`;
});
@Module({
  imports: [ConfigModule.forRoot({
    isGlobal: true,
    load: [configuration]
  }),
  WinstonModule.forRoot({
    exitOnError: false,
    format: winston.format.combine(winston.format.timestamp()
    , winston.format.label({ label: path.basename(process.mainModule.filename) })
    ,myFormat),  // winston.format.json(),
    transports: [
        new (<any>(winston.transports)).DailyRotateFile({
            filename: '/Desktop/logs/daily-%DATE%.log',
            datePattern: 'YYYY-MM-DD',
            maxFiles: '14d'
        }),
        new winston.transports.Console({
          format: winston.format.combine(winston.format.timestamp(), myFormat),
          handleExceptions: true
        })
    ],
    exceptionHandlers: [
        new winston.transports.File({ filename: '/Desktop/logs/exception.log' }),
    ]
  }),],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
The console directly print below but there is no content in the file `/Desktop/logs/exception.log`
```
[Nest] 66966   - 07/16/2020, 8:21:33 PM   [ExceptionsHandler] ER_NO_SUCH_TABLE: Table 'test.aaaaa11111' doesn't exist +4038ms
Error: ER_NO_SUCH_TABLE: Table 'test.aaaaa11111' doesn't exist
    at Query.Sequence._packetToError (/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/node_modules/mysql/lib/Connection.js:198:25)
    at /dist/src/common/MySqlService.js:63:28
    at Handshake.onConnect (/node_modules/mysql/lib/Pool.js:64:7)
    at Handshake.<anonymous> (/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.Sequence.OkPacket (/node_modules/mysql/lib/protocol/sequences/Sequence.js:92:8)
    at Protocol._parsePacket (/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/node_modules/mysql/lib/protocol/Parser.js:433:10)
```

**Comment by marcelom56** [comment]
@likepeach789 did you found a solution about it? I am having the same problem here.

**Comment by gremo** [comment]
I think (just guessing) that the exception handler works only when this module is used as main Nest logger. Can we make a quick teest? So I can also updated the documentation. Thanks both.

**Comment by gremo** [comment]
I thinks it's an old issues from the `winston` package, see https://github.com/winstonjs/winston/issues/1613 and https://github.com/winstonjs/winston/issues/886 and https://github.com/winstonjs/winston/issues/1802.

I did a quick test and can't get it to work. Feel free to comment this issue again if you think that is a fault of this module, thanks!

**Comment by new-immersion** [comment]
For those facing this issue, you can create an ExceptionFilter to capture exceptions, import the logger into it, and log the exceptions within the catch() function.

```typescript
import { ArgumentsHost, Catch } from '@nestjs/common';
import { BaseExceptionFilter, HttpAdapterHost } from '@nestjs/core';
import { Logger } from 'winston';

@Catch()
export class AllExceptionsFilter extends BaseExceptionFilter {
  constructor(
    readonly httpAdapterHost: HttpAdapterHost,
    private readonly logger: Logger,
  ) {
    super(httpAdapterHost.httpAdapter);
  }

  catch(exception: unknown, host: ArgumentsHost) {
    this.logger.error(exception);
    super.catch(exception, host);
  }
}
```
```typescript
import { HttpAdapterHost, NestFactory } from '@nestjs/core';
import { WINSTON_MODULE_PROVIDER } from 'nest-winston';
import { AllExceptionsFilter } from './all-exceptions.filter';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const httpAdapterHost = app.get(HttpAdapterHost);
  const logger = app.get(WINSTON_MODULE_PROVIDER);
  app.useGlobalFilters(new AllExceptionsFilter(httpAdapterHost, logger)); 
  await app.listen(process.env.PORT ?? 3000);
}
bootstrap();
```
