### ISSUE TITLE
Using as Main logger: fails for unit tests: RootTestModule

### ISSUE THREAD

**Issue by bitsofinfo** [gremo/nest-winston#235]
I followed the directions to use this as the main logger, and I am importing the Logger and LoggerService per the readme in a class that a unit test utilizes. Just running the app, things work fine, however with I `npm run test` I get this

```
   Nest can't resolve dependencies of the ApiTokenService (ConfigService, HttpService, ?). Please make sure that the argument Logger at index [2] is available in the RootTestModule context.

    Potential solutions:
    - If Logger is a provider, is it part of the current RootTestModule?
    - If Logger is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing Logger */ ]
      })

```

**Comment by bitsofinfo** [comment]
I get the same thing just trying the quick start method

```
    Nest can't resolve dependencies of the ApiTokenService (ConfigService, HttpService, ?). Please make sure that the argument winston at index [2] is available in the RootTestModule context.

    Potential solutions:
    - If winston is a provider, is it part of the current RootTestModule?
    - If winston is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing winston */ ]
      })
```

**Comment by gremo** [comment]
Hi, are you able to setup a minimal github repo as an example?

**Comment by a1rwulf** [comment]
Has anyone ever found a solution to this?
I'm seeing the same error using the samples of this project.
Using node 18.16.1

Reproduction:
```
git clone git@github.com:gremo/nest-winston.git
cd nest-winston/sample/replace-nest-logger-bootstrap
npm ci
npm run test:cov
```

Fails like this:
```
15:50 $ npm run test:cov

> sample-replace-nest-logger-bootstrap@1.0.0 test:cov
> jest --coverage

 FAIL  src/app.controller.spec.ts
  AppController
    root
      ✕ should return "Hello World!" (12 ms)

  ● AppController › root › should return "Hello World!"

    Nest can't resolve dependencies of the AppController (AppService, ?). Please make sure that the argument Logger at index [1] is available in the RootTestModule context.

    Potential solutions:
    - If Logger is a provider, is it part of the current RootTestModule?
    - If Logger is exported from a separate @Module, is that module imported within RootTestModule?
      @Module({
        imports: [ /* the Module containing Logger */ ]
      })

      at Injector.lookupComponentInParentModules (../node_modules/@nestjs/core/injector/injector.js:188:19)
      at Injector.resolveComponentInstance (../node_modules/@nestjs/core/injector/injector.js:144:33)
      at resolveParam (../node_modules/@nestjs/core/injector/injector.js:98:38)
          at async Promise.all (index 1)
      at Injector.resolveConstructorParams (../node_modules/@nestjs/core/injector/injector.js:113:27)
      at Injector.loadInstance (../node_modules/@nestjs/core/injector/injector.js:46:9)
      at Injector.loadController (../node_modules/@nestjs/core/injector/injector.js:59:9)
          at async Promise.all (index 0)
      at InstanceLoader.createInstancesOfControllers (../node_modules/@nestjs/core/injector/instance-loader.js:52:9)
      at ../node_modules/@nestjs/core/injector/instance-loader.js:30:13
```

I also tried the `quick-start` and the `replace-nest-logger` sample and all fail in the very same way.
Any ideas how to resolve this?
