### ISSUE TITLE
error stack trace is not printed

### ISSUE THREAD

**Issue by TrejGun** [gremo/nest-winston#73]
Hi there! I'm not sure if this is feature request of bug repport.

what I do is configure winson in bootstrap function
```js
  app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER));
```

and app module
```js
    WinstonModule.forRootAsync({
      useFactory: () => ({
        transports: [
          new transports.Console({
            format: format.combine(
              format.timestamp(),
              utilities.format.nestLike(),
            ),
          }),
        ],
      }),
    }),
```

and then use

```js
  constructor(@Inject("winston") private readonly logger: Logger) {}

  public method(): void {
    const error = new Error("On no!");
    this.logger.error(error.message, error.stack, this.constructor.name);
  }
```

which print just 
```
[NestWinston] Error     11/30/2019, 9:47:02 PM On no! - {}
```

according to docs it should print [context] and `trace` property in the meta data

ok lets do this ather way around

```js
  constructor(@Inject("winston") private readonly logger: Logger) {}

  public method(): void {
    const error = new Error("On no!");
    this.logger.error(error);
  }
```

prints 
```
[NestWinston] Error     11/30/2019, 9:51:27 PM undefined - {}
```
which is even worth

I was managed to make it work somehow
```js
    WinstonModule.forRootAsync({
      useFactory: () => ({
        format: format.combine(
          format.errors({stack: true}), 
          format.timestamp()
        ),
        transports: [
          new transports.Console({
            format: format.printf(({level, context, timestamp, message, stack, trace}) => {
              let color, text;
              if (level === "error") {
                color = red;
                const lines = (stack || trace).split("\n");
                lines[0] = color(lines[0]);
                text = lines.join("\n");
              } else {
                color = green;
                text = color(message);
              }
              return `${color(`[Nest] ${process.pid}   -`)} ${new Date(timestamp).toLocaleString()}   ${context ? yellow("[" + context + "]") : ""} ${text}`;
            }),
          }),
        ],
      }),
    }),
```
now it prints Error object

```
[Nest] 20905   - 11/30/2019, 9:53:37 PM    Error: On no!
    at AuthController.biometric (~/path/to/file.ts:59:19)
    at ~/node_modules/@nestjs/core/router/router-execution-context.js:37:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ~/node_modules/@nestjs/core/router/router-execution-context.js:45:28
    at ~/node_modules/@nestjs/core/router/router-proxy.js:8:17
```

but i still want to pass context and signature with 3 params just does not work. Please gimme some directions

**Comment by gremo** [comment]
@Piranit can you help me with this?

**Comment by TrejGun** [comment]
i can, what kind of help do you need?

**Comment by gremo** [comment]
@TrejGun I don't know how error loggin works, so I was asking to him how stack trace is printed: is this a bug or something to be implemented?

**Comment by TrejGun** [comment]
it is impleneted and used for example in here
https://github.com/nestjs/nest/blob/master/packages/core/exceptions/base-exception-filter.ts#L55

and also implemented in your code
https://github.com/gremo/nest-winston/blob/master/src/winston.providers.ts#L13

but for some reason does not work, probably arguments are messed up when passed from nest to winston

**Comment by TrejGun** [comment]
ok I know what is wrong.

I have to inject WINSTON_MODULE_NEST_PROVIDER instead of WINSTON_MODULE_PROVIDER
